### PR TITLE
Access to Rate Limit Headers

### LINKED ISSUE #11: Access to Rate Limit Headers
I would appreciate if following a request the rate limit, amount remaining and time remaining where available by a method call on the provider.

https://dev.fitbit.com/docs/basics/#rate-limits

I want to suggest something like the following, but want to leave it up to you to match your style and the best interest of the rest of the users.

```

    /**
     * @var string
     */
    protected $limit;

    /**
     * @var string
     */
    protected $remaining;

    /**
     * @var string
     */
    protected $reset;

protected function checkResponse(ResponseInterface $response, $data)
    {

        $this->limit = $response->getHeader('Fitbit-Rate-Limit-Limit')[0];
        $this->remaining = $response->getHeader('Fitbit-Rate-Limit-Remaining')[0];
        $this->reset = $response->getHeader('Fitbit-Rate-Limit-Reset')[0];

        if (!empty($data['errors'][0])) {
            $message = $data['errors'][0]['errorType'] . ': ' . $data['errors'][0]['message'];
            throw new IdentityProviderException($message, $response->getStatusCode(), $data);
        }
    }

public function getRateLimit(){
            return $this->limit;
}

public function getRateRemaining(){
            return $this->remaining;
}

public function getRateReset(){
            return $this->reset;
}
```

If you would like me to test and do a formal pull request I'm willing, if that will help this get integrated faster.

Thanks
Brad

### PR DESCRIPTION
**Pull request by djchen**
Fixes #11

### CODE REVIEW

File: src/Provider/FitbitRateLimit.php [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+    {
+        return $retryAfter;
+    }
+
+    /**
+     * @return String The quota number of calls.
+     */
+    public function getLimit()
+    {
+        return $limit;
```
Comment (stof) [inline src/Provider/FitbitRateLimit.php:41]: this implementation is totally broken, as it uses undefined local variables. And as there is no tests for this class, it was not catched on CI (btw, you could enable scrutinizer-ci which would detect such mistakes through static analysis)

Comment (djchen) [reply src/Provider/FitbitRateLimit.php:41]: Is there a free version of scruitinizer-ci?

Comment (stof) [reply src/Provider/FitbitRateLimit.php:41]: it is free for public repos
